### ISSUE TITLE
Subsequent Launches of Emacs load no packages

### ISSUE THREAD

**Issue by 0x4d6165** [radian-software/straight.el#1104] opened 2023-07-09 17:19 UTC
I have an emacs.d setup that I've been using for some time https://git.sr.ht/~x4d6165/.emacs.d but now I'm getting an issue where a clean clone of my .emacs.d repo produces a working setup but if I close and reopen emacs, no packages are loaded and the straight-process shows that it's trying run find on a bunch of directories with the return code being 0. I can't tell if this is a bug or an error on my part but I haven't changed anything in my .emacs.d so I have no idea what could've changed.

**Comment by progfolio** [comment] 2023-07-11 22:33
Has the emacs version changed at all?

**Comment by raxod502** [comment] 2023-07-12 23:23
Also check that the problem is not your byte-compiled init-file. Byte-compiling the init-file is hard to do right. It's also a little unusual that you have it checked into source control; in general, the byte-compiled artifacts are system-dependent.

**Comment by 0x4d6165** [comment] 2023-07-14 18:32
Oh shoot, that was checked in accidentally, thanks for pointing that out. Emacs version hasn't changed. I will say the error hasn't happened since and I'm not exactly sure what changed that made it start working again? Very strange. --debug-init didn't yield any information when the error was happening and my straight version is `prerelease (HEAD -> master, origin/master, origin/develop, origin/HEAD) ff63b15 2023-06-15`

**Comment by progfolio** [comment] 2023-07-14 19:59
Thanks for following up with us. We'll consider this closed. If you run into the issue again, comment and we can reopen.

**Closed by progfolio** 2023-07-14 19:59 UTC
Labels: support
