### ISSUE TITLE
Emacs 29.1 support

### ISSUE THREAD

**Issue by RaulPPelaez** [radian-software/straight.el#1076] opened 2023-04-11 07:41 UTC
Current master fails to bootstrap using emacs 29.0.90 with the following error:

```elisp
Debugger entered--Lisp error: (void-variable native-comp-deferred-compilation-deny-list)
  straight--build-native-compile((:type git :host github :repo "radian-software/straight.el" :files ("straight*.el") :branch "master" :package "straight" :local-repo "straight.el"))
  straight--build-package((:type git :host github :repo "radian-software/straight.el" :files ("straight*.el") :branch "master" :package "straight" :local-repo "straight.el") nil)
  #f(compiled-function () #<bytecode 0x7cf19944a8f5436>)()
  straight--transaction-exec(use-package-\"c809124e9c5270ea1c72e2c3507331d1\"-nil-nil :now #f(compiled-function () #<bytecode 0x7cf19944a8f5436>))
  straight-use-package((straight :type git :host github :repo "radian-software/straight.el" :files ("straight*.el") :branch "master"))
  eval-buffer(#<buffer  *load*-100331> nil "/home/user/.emacs.d/straight/repos/straight.el/boo..." nil t)  ; Reading at buffer position 5397
  load-with-code-conversion("/home/user/.emacs.d/straight/repos/straight.el/boo..." "/home/user/.emacs.d/straight/repos/straight.el/boo..." nil t)
  load("/home/user/.emacs.d/straight/repos/straight.el/boo..." nil nomessage)
  (let ((bootstrap-file (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory)) (bootstrap-version 5)) (if (file-exists-p bootstrap-file) nil (save-current-buffer (set-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straigh..." #'silent #'inhibit-cookies)) (goto-char (point-max)) (eval-print-last-sexp))) (load bootstrap-file nil 'nomessage))
  eval-buffer(#<buffer  *load*> nil "/home/user/.emacs" nil t)  ; Reading at buffer position 825
  load-with-code-conversion("/home/user/.emacs" "/home/user/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0xd489cb3187ae488>) #f(compiled-function () #<bytecode -0x1f3c61addc0b39f5>) t)
  command-line()
  normal-top-level()
```
The variable  native-comp-deferred-compilation-deny-list seems to have changed to  native-comp-jit-compilation-deny-list.
One can go around this error by setting the old variable before loading straight:
```elisp
(setq native-comp-deferred-compilation-deny-list nil)
```

**Comment by progfolio** [comment] 2023-04-11 15:23
Duplicate of https://github.com/radian-software/straight.el/issues/1059

Please search past issues prior to creating a new one.

**Closed** 2023-04-11 15:24 UTC
Labels: feature
