### ISSUE TITLE
nongnu-elpa update is stuck

### ISSUE THREAD

**Issue by ayrat555** [radian-software/straight.el#1033] opened 2022-12-26 08:59 UTC
## What's wrong

fetching emacs mirror is stuck during non-gnu elpa fetching. Disabling emacsmirror fixes the problem:
```elisp
(setq straight-recipes-emacsmirror-use-mirror nil)
(setq straight-recipes-gnu-elpa-use-mirror nil)
```

**Comment by progfolio** [comment] 2022-12-26 18:18
See: #996 #994

**Comment by progfolio** [comment] 2022-12-26 18:21
Unable to reproduce on my end:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (message "done"))
```
</details>

- Test run at: `2022-12-26 13:22:55`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 05caec1 2022-12-22`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.35, cairo version 1.17.6)
 of 2022-12-18`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 05caec1 2022-12-22
done
Packages:
"straight"                n/a                  develop 05caec1 2022-12-22
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 835c996c 2022-12-20
"gnu-elpa-mirror"         n/a                  master eb11995 2022-12-15
"nongnu-elpa"             n/a                  main b552c02813 2022-12-21
"el-get"                  melpa                master d28d6179 2022-12-08
"emacsmirror-mirror"      n/a                  master 8bd0781 2022-12-22


```
</details>

Perhaps there was a temporary networking issue.
You can try evaluating the above test case to see if it works now.

**Comment by ayrat555** [comment] 2022-12-26 18:38
unfortunately it's not a temporary issue I was struggling with it a couple of hours yesterday and some time today

**Comment by progfolio** [comment] 2022-12-26 18:42
Are you able to manually clone the repository from the command line?
e.g.

> git clone https://github.com/emacs-straight/emacsmirror-mirror /tmp/emacs-mirror.test

**Comment by ayrat555** [comment] 2022-12-27 07:05
@progfolio yes, I'm able to do it. but I think the issue is in non-gnu elpa. maybe it's a dependency of emacsmirror?

**Comment by progfolio** [comment] 2022-12-27 18:38
It's not a dependency of emacsmirror.
How about manually cloning the nongnu elpa repo? Does that work?
e.g.

> git clone  "https://git.savannah.gnu.org/git/emacs/nongnu.git" /tmp/nongnu.test

**Comment by ayrat555** [comment] 2022-12-28 06:37
@progfolio it works but  it takes forever to clone. maybe that's the root cause

**Comment by progfolio** [comment] 2022-12-28 06:57
Ok. This is a duplicate of #996. You can also see #994.

**Closed** 2022-12-28 07:36 UTC
Labels: support
