### ISSUE TITLE
NonGNU ELPA changed package list format

### ISSUE THREAD

**Issue by amnore** [radian-software/straight.el#1012] opened 2022-11-25 04:30 UTC
## What's wrong

They now use symbols for package names. This causes `straight-recipes-nongnu-elpa-retrieve` https://github.com/radian-software/straight.el/blob/f21103d97d180fba0b6e2e86ebb0b6269219ef2c/straight.el#L3373-L3378 to throw an error. See https://git.savannah.gnu.org/cgit/emacs/nongnu.git/commit/?id=20e4ce4ff661d449065eb646fd4569d147eb4191

### Version information

* Emacs version: N/A
* Operating system: N/A

**Comment by mkvoya** [comment] 2022-11-25 04:42
Removing the invocation of `intern` seems to fix.

```emacs-lisp
:key (lambda (it) (car it)))))
```

**Comment by progfolio** [comment] 2022-11-25 04:45
Thanks for the heads up. We can make use of cl-find's :key and :test keywords here instead of the lambda.

**Comment by progfolio** [comment] 2022-11-25 05:24
I've merged a fix to the "develop" branch. Testing appreciated. Thank you.

**Closed by progfolio** 2022-11-25 05:24 UTC
Labels: bug

**Comment by mkvoya** [comment] 2022-11-25 06:42
Just encountered another problem with the fixed version.
It might be caused by the `intern` call in `straight-recipes-nongnu-elpa--translate`.

```emacs-lisp
(defun straight-recipes-nongnu-elpa--translate (recipe)
  "Translate RECIPE into straight.el-style recipe."
  (unless (null recipe)
    (let ((name (pop recipe)))
      `( ,(intern name)
         :repo ,(plist-get recipe :url)
         ,@(when-let ((ignored (plist-get recipe :ignored-files)))
             `(:files (:defaults (:exclude ,@ignored))))))))

```

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/10482293/203916568-4825fe5b-0106-4659-82c8-f0e27b2b1b09.png">

**Comment by progfolio** [comment] 2022-11-25 06:48
Both the master and develop branches should be pointing to:

https://github.com/radian-software/straight.el/commit/3eca39dfc6797243ec7d1c6a7d45142407f73f88

Are you running the latest version of straight.el?

**Comment by mkvoya** [comment] 2022-11-25 07:00
> Both the master and develop branches should be pointing to:
> 
> [3eca39d](https://github.com/radian-software/straight.el/commit/3eca39dfc6797243ec7d1c6a7d45142407f73f88)
> 
> Are you running the latest version of straight.el?

My bad. The latest version [3eca39d](https://github.com/radian-software/straight.el/commit/3eca39dfc6797243ec7d1c6a7d45142407f73f88) works well.
