### ISSUE TITLE
Some package names not appearing in the selection list for M-x straight-get-recipe 

### ISSUE THREAD

**Issue by YorkZ** [radian-software/straight.el#1016] opened 2022-11-26 19:01 UTC
For example, I wanted to get the recipe for the package `anki-editor`, so I run `M-x straight-get-recipe`. However, `anki-editor` doesn't show up in the `completing-read` selection list. I then looked at the related source code in `straight-get-recipe`:

``` emacs-lisp
(completing-read
 "Which recipe? "
 (cl-remove-if (lambda (pkg)
                 (gethash pkg straight--repo-cache))
               (straight-recipes-list sources))
 (lambda (_) t)
 'require-match)
```

According to the above code, my understanding is that the package has been removed from the list returned from `(straight-recipes-list sources)` which I don't understand why. I then evaluated the following expression manually:

``` emacs-lisp
(gethash "anki-editor" straight--repo-cache)
```

which returned the following recipe:

```
(:type git :flavor melpa :host github :repo "louietan/anki-editor" :package "anki-editor" :local-repo "anki-editor")
```

So it seems that this confirmed that the recipe for `anki-editor` has been removed from the `completing-read` selection list which I don't understand why. Could you please explain to me? Thank you.

**Comment by progfolio** [comment] 2022-11-26 19:29
Please include the output of `straight-version`.

**Comment by YorkZ** [comment] 2022-11-26 19:36
The output of `M-x straight-version` was `prerelease (HEAD -> master, origin/master, origin/HEAD) 4517e11 2022-04-13`

**Comment by progfolio** [comment] 2022-11-26 19:53
This is a duplicate of https://github.com/radian-software/straight.el/issues/976
Please see that issue for an explanation.

**Comment by YorkZ** [comment] 2022-11-26 20:39
Thank you @progfolio and great work, so I'll wait for PR 1017 to be merged.

**Comment by progfolio** [comment] 2022-11-26 20:52
You're welcome. I've merged the change into the "develop" branch. Testing is appreciated.

**Comment by YorkZ** [comment] 2022-11-27 05:15
Thanks @progfolio, your fix works.

By the way, this is how I used the `develop` branch:

1. Add 

   ``` emacs-lisp
   (defvar straight-repository-branch)
   (setq straight-repository-branch "develop")
   ```
   to bootstrap snippet so it becomes:
   
   ``` emacs-lisp
   (defvar bootstrap-version)
   (let ((bootstrap-file
          (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
         (bootstrap-version 6))
     (defvar straight-repository-branch)
     (setq straight-repository-branch "develop")
     (unless (file-exists-p bootstrap-file)
       (with-current-buffer
           (url-retrieve-synchronously
            "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
            'silent 'inhibit-cookies)
         (goto-char (point-max))
         (eval-print-last-sexp)))
     (load bootstrap-file nil 'nomessage))
   ```
2. Delete the directory `~/.emacs.d/straight/repos/straight.el`
3. Restart `Emacs`

Is this the best practice for using `develop` branch? Also instead of deleting the directory `~/.emacs.d/straight/repos/straight.el`, can I just delete the file `~/.emacs.d/straight/repos/straight.el/bootstrap.el`?

**Comment by progfolio** [comment] 2022-11-28 02:38
You have the right idea to get going on the develop branch. I would stick with that instead of deleting just bootstrap.el.

**Closed by progfolio** 2022-11-28 02:38 UTC
Labels: support
