### ISSUE TITLE
xah-fly-keys package fails to install

### ISSUE THREAD

**Issue by g3r** [radian-software/straight.el#989] opened 2022-08-16 12:18 UTC
## What's wrong

The package xah-fly-keys fails to install:
I git bisect straight and the culprit commit is 5fb04bcf84a0532157c999cdf06ec64e4ff10409

## Directions to reproduce
```(straight-use-package '(xah-fly-keys :host github :repo "g3r/xah-fly-keys"))```

eval-last-sexp:
```Debugger entered--Lisp error: (error "Invalid sub-list head in :files directive: :not")
  error("Invalid sub-list head in :files directive: %S" :not)
  straight--expand-files-directive-internal((:defaults (:not "*.png")) "/home/german/.emacs.d/straight/repos/xah-fly-keys/" "" nil)
  straight-expand-files-directive((:defaults (:not "*.png")) "/home/german/.emacs.d/straight/repos/xah-fly-keys/" "/home/german/.emacs.d/straight/build/xah-fly-keys/" nil)
  straight--symlink-package((:host github :repo "g3r/xah-fly-keys" :files (:defaults (:not "*.png")) :package "xah-fly-keys" :type git :local-repo "xah-fly-keys"))
  straight--build-package((:host github :repo "g3r/xah-fly-keys" :files (:defaults (:not "*.png")) :package "xah-fly-keys" :type git :local-repo "xah-fly-keys") nil)
  #f(compiled-function () #<bytecode -0xbdaa8c84fb3040e>)()
  straight--transaction-exec(use-package-\"6d611e8809a9a00c62d5930d0a7276bd\"-nil-nil :now #f(compiled-function () #<bytecode -0xbdaa8c84fb3040e>))
  straight-use-package((xah-fly-keys :host github :repo "g3r/xah-fly-keys" :files (:defaults (:not "*.png"))))
  (progn (straight-use-package '(xah-fly-keys :host github :repo "g3r/xah-fly-keys" :files (:defaults (:not "*.png")))))
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  command-execute(eval-last-sexp)
```
This is my fork of xah-fly-keys, but I also tried the upstream version with the same result.
Adding ```(:files "*.el")``` to the recipe fixes the issue

### Version information

* Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-08-14
* Operating system: Manjaro Linux

**Comment by progfolio** [comment] 2022-08-19 17:22
Reproducible with the following:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'xah-fly-keys))
```
</details>

- Test run at: `2022-08-19 12:43:41`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 749f7f0 2022-08-11`
- emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-08-18`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 749f7f0 2022-08-11
Cloning xah-fly-keys...
Cloning xah-fly-keys...done
Building xah-fly-keys...

Packages:
"straight"                n/a                  develop 749f7f0 2022-08-11
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 76cd5a26 2022-08-18
"gnu-elpa-mirror"         n/a                  master 4ac6403 2022-08-17
"nongnu-elpa"             n/a                  main baad781689 2022-07-24
"el-get"                  melpa                master bf3dba44 2022-06-02
"emacsmirror-mirror"      n/a                  master 1c29217 2022-08-11

Error: (error "Invalid sub-list head in :files directive: :not")

```
</details>

That's because we

**Comment by progfolio** [comment] 2022-08-19 17:33
That was an error on my part when implementing NonGNU ELPA support.
`:not` is a straight-specific keyword used in conjunction with `:build`.
I accidentally used that instead of the `:exclude` keyword used with `:files`.

Fixed on the develop branch:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'xah-fly-keys)
  (let
      ((default-directory
        (straight--build-dir "xah-fly-keys")))
    (message "%S"
             (straight--process-output "ls" "-lah"))))
```
</details>

- Test run at: `2022-08-19 13:30:24`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) f21103d 2022-08-19`
- emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-08-18`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) f21103d 2022-08-19
Cloning xah-fly-keys...
Cloning xah-fly-keys...done
Building xah-fly-keys...
Building xah-fly-keys...done

"total 124K
drwxr-xr-x 2 n n  100 Aug 19 13:30 .
drwxr-xr-x 4 n n   80 Aug 19 13:30 ..
-rw-r--r-- 1 n n 1.7K Aug 19 13:30 xah-fly-keys-autoloads.el
lrwxrwxrwx 1 n n   72 Aug 19 13:30 xah-fly-keys.el -> /tmp/straight.el-test-1IQuen/straight/repos/xah-fly-keys/xah-fly-keys.el
-rw-r--r-- 1 n n 118K Aug 19 13:30 xah-fly-keys.elc"
Packages:
"straight"                n/a                  develop f21103d 2022-08-19
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 76cd5a26 2022-08-18
"gnu-elpa-mirror"         n/a                  master 4ac6403 2022-08-17
"nongnu-elpa"             n/a                  main baad781689 2022-07-24
"el-get"                  melpa                master bf3dba44 2022-06-02
"emacsmirror-mirror"      n/a                  master 1c29217 2022-08-11
"xah-fly-keys"            nongnu-elpa          master df9284f 2022-08-12


```
</details>

Thank you for the report.

**Closed by progfolio** 2022-08-19 17:33 UTC
Labels: bug
